
# Generated by Django 4.2.21 on 2025-05-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deposit", "정기예금"),
                            ("saving", "적금"),
                            ("stock", "주식"),
                            ("etf", "ETF"),
                            ("goods", "현물"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("link", models.URLField(blank=True)),
                ("interest_rate", models.FloatField(blank=True, null=True)),
                ("special_rate", models.FloatField(blank=True, null=True)),
                ("term", models.CharField(blank=True, max_length=100, null=True)),
                ("target", models.CharField(blank=True, max_length=100, null=True)),
                ("stock_code", models.CharField(blank=True, max_length=20, null=True)),
                ("market_type", models.CharField(blank=True, max_length=50, null=True)),
                ("current_price", models.FloatField(blank=True, null=True)),
                ("price_change", models.FloatField(blank=True, null=True)),
                ("sector", models.CharField(max_length=10)),
                (
                    "warning_info",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("open_price", models.FloatField(blank=True, null=True)),
                ("high_price", models.FloatField(blank=True, null=True)),
                ("low_price", models.FloatField(blank=True, null=True)),
                ("base_price", models.FloatField(blank=True, null=True)),
                ("weighted_avg_price", models.FloatField(blank=True, null=True)),
                ("high_52w", models.FloatField(blank=True, null=True)),

            
                ("high_52w_date", models.DateField(blank=True, null=True)),
                ("low_52w", models.FloatField(blank=True, null=True)),
                ("low_52w_date", models.DateField(blank=True, null=True)),
                ("per", models.FloatField(blank=True, null=True)),
                ("pbr", models.FloatField(blank=True, null=True)),
                ("eps", models.FloatField(blank=True, null=True)),
                ("bps", models.FloatField(blank=True, null=True)),
                ("market_cap", models.FloatField(blank=True, null=True)),
                ("listed_shares", models.IntegerField(blank=True, null=True)),
                (
                    "settlement_month",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("per_value", models.FloatField(blank=True, null=True)),
                ("trade_volume", models.IntegerField(blank=True, null=True)),
                ("trade_value", models.FloatField(blank=True, null=True)),
                ("foreign_ownership", models.FloatField(blank=True, null=True)),
                ("short_selling_allowed", models.BooleanField(blank=True, null=True)),
                ("short_selling_volume", models.IntegerField(blank=True, null=True)),
                ("nav", models.FloatField(blank=True, null=True)),
                ("nav_change", models.FloatField(blank=True, null=True)),

            ],
        ),
    ]
