# Generated by Django 4.2.21 on 2025-05-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("published_at", models.DateTimeField()),
            ],
        ),
    ]
