# Generated by Django 4.2.21 on 2025-05-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocknews",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
