# Generated by Django 4.2.21 on 2025-05-24 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("conservative", "안정형"),
                            ("moderate", "중립형"),
                            ("aggressive", "공격형"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_score", models.IntegerField()),
                ("q1_age", models.IntegerField()),
                ("q2_experience", models.IntegerField()),
                ("q3_loss_response", models.IntegerField()),
                ("q4_income", models.IntegerField()),
                ("q5_expected_return", models.IntegerField()),
                ("q6_emergency", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
