# Generated by Django 4.2.20 on 2025-05-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='q1_age',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='q2_experience',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='q3_loss_response',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='q4_income',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='q5_expected_return',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='q6_emergency',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='total_score',
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_data',
            field=models.JSONField(default=dict),
        ),
    ]
