# Generated by Django 4.2.21 on 2025-05-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_solved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="board_type",
            field=models.CharField(
                choices=[("free", "자유게시판"), ("question", "질문게시판")],
                max_length=8,
            ),
        ),
    ]
