# Generated by Django 4.2.21 on 2025-05-24 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "bank_type",
                    models.CharField(
                        choices=[
                            ("KB", "KB국민은행"),
                            ("SH", "신한은행"),
                            ("WR", "우리은행"),
                            ("NH", "농협은행"),
                            ("IBK", "기업은행"),
                            ("KEB", "하나은행"),
                            ("SC", "SC제일은행"),
                            ("CT", "씨티은행"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "operating_hours",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "region_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banks",
                        to="regions.regioncity",
                    ),
                ),
                (
                    "region_district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banks",
                        to="regions.regiondistrict",
                    ),
                ),
            ],
            options={
                "ordering": ["bank_type", "name"],
            },
        ),
    ]
